{
  "formatVersion": "1.1",
  "component": {
    "group": "me.kujio",
    "module": "kandroidutils",
    "version": "1.5.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "kandroidutils-1.5.2.aar",
          "url": "kandroidutils-1.5.2.aar",
          "size": 157812,
          "sha512": "a144ecc7f8ec550a0298a62acc51b6e6719f91f0d610b286f9622c256d4689c146a3509f37df322db604bcec6419a1ea49bbac3e2ce52936fcbfbb76ecceeea1",
          "sha256": "89813f808f82a9add5a745b541f350191f0365b2126cb3ea94939febcc0d2e69",
          "sha1": "c38794db92c4fbc5e9b37a45efe066c7d425ff53",
          "md5": "27b40fc0ff4fd26ad37d295bfc5c36b3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "kandroidutils-1.5.2.aar",
          "url": "kandroidutils-1.5.2.aar",
          "size": 157812,
          "sha512": "a144ecc7f8ec550a0298a62acc51b6e6719f91f0d610b286f9622c256d4689c146a3509f37df322db604bcec6419a1ea49bbac3e2ce52936fcbfbb76ecceeea1",
          "sha256": "89813f808f82a9add5a745b541f350191f0365b2126cb3ea94939febcc0d2e69",
          "sha1": "c38794db92c4fbc5e9b37a45efe066c7d425ff53",
          "md5": "27b40fc0ff4fd26ad37d295bfc5c36b3"
        }
      ]
    }
  ]
}
