{
  "formatVersion": "1.1",
  "component": {
    "group": "me.kujio",
    "module": "kandroidutils",
    "version": "1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "kandroidutils-1.1.aar",
          "url": "kandroidutils-1.1.aar",
          "size": 98324,
          "sha512": "f90f4d973c8ec22d19df60b19b098ba33ea3d5b85823df5b90675ab6832d95ecdbbbcb5bc84391bcaab8994c06f919fb9bb895e389f6edc7b1cf0cc71f7ec24c",
          "sha256": "d75c77c2c0b693675819a6841675e6d6b57d9e0ee9fe6e9c5c3a65696f3eddaf",
          "sha1": "5792720f0cb2e321311b936783067fd26a79dd57",
          "md5": "f677d872b20f945f1163de9f617d0e27"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "kandroidutils-1.1.aar",
          "url": "kandroidutils-1.1.aar",
          "size": 98324,
          "sha512": "f90f4d973c8ec22d19df60b19b098ba33ea3d5b85823df5b90675ab6832d95ecdbbbcb5bc84391bcaab8994c06f919fb9bb895e389f6edc7b1cf0cc71f7ec24c",
          "sha256": "d75c77c2c0b693675819a6841675e6d6b57d9e0ee9fe6e9c5c3a65696f3eddaf",
          "sha1": "5792720f0cb2e321311b936783067fd26a79dd57",
          "md5": "f677d872b20f945f1163de9f617d0e27"
        }
      ]
    }
  ]
}
