{
  "formatVersion": "1.1",
  "component": {
    "group": "me.kujio",
    "module": "kandroidutils",
    "version": "1.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "kandroidutils-1.4.1.aar",
          "url": "kandroidutils-1.4.1.aar",
          "size": 177109,
          "sha512": "4204e49b47c0752a6889934c819ed684aebf9e11c8cf9374ddb2a3960c6630e0be5c80a2e7579b39b2c81ad9d7ab8cbcd8712edb756921c5246cac2849be5ee4",
          "sha256": "0d564932321eaa067e93fbba43e70860c6282663afc8c87d201309e2b8575386",
          "sha1": "641ddf6a32e0523fa7d4b4bbc74c792fa1bb474e",
          "md5": "50346b60be6c3982bae29fa4f9c6c291"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "kandroidutils-1.4.1.aar",
          "url": "kandroidutils-1.4.1.aar",
          "size": 177109,
          "sha512": "4204e49b47c0752a6889934c819ed684aebf9e11c8cf9374ddb2a3960c6630e0be5c80a2e7579b39b2c81ad9d7ab8cbcd8712edb756921c5246cac2849be5ee4",
          "sha256": "0d564932321eaa067e93fbba43e70860c6282663afc8c87d201309e2b8575386",
          "sha1": "641ddf6a32e0523fa7d4b4bbc74c792fa1bb474e",
          "md5": "50346b60be6c3982bae29fa4f9c6c291"
        }
      ]
    }
  ]
}
