{
  "formatVersion": "1.1",
  "component": {
    "group": "me.kujio",
    "module": "kandroidutils",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "kandroidutils-1.0.aar",
          "url": "kandroidutils-1.0.aar",
          "size": 96818,
          "sha512": "74a579297e52f9ae89009b48bc17ce4b57070d5c1b23e9450b19efdf19d3163a24649187eedde063f411e8dc6993a1d86cb042d0b39ce3f8d7ae947acd815508",
          "sha256": "8f183b76e91db501dbdabf082e83ea466c8f9f492ae1c458a4f76e18be5d4358",
          "sha1": "ad867447111fe3476a7cf113cba4a2a915b77586",
          "md5": "f1acef01b107bccd339af14d841bc465"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "kandroidutils-1.0.aar",
          "url": "kandroidutils-1.0.aar",
          "size": 96818,
          "sha512": "74a579297e52f9ae89009b48bc17ce4b57070d5c1b23e9450b19efdf19d3163a24649187eedde063f411e8dc6993a1d86cb042d0b39ce3f8d7ae947acd815508",
          "sha256": "8f183b76e91db501dbdabf082e83ea466c8f9f492ae1c458a4f76e18be5d4358",
          "sha1": "ad867447111fe3476a7cf113cba4a2a915b77586",
          "md5": "f1acef01b107bccd339af14d841bc465"
        }
      ]
    }
  ]
}
