{
  "formatVersion": "1.1",
  "component": {
    "group": "me.kujio",
    "module": "kandroidutils",
    "version": "1.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "kandroidutils-1.6.0.aar",
          "url": "kandroidutils-1.6.0.aar",
          "size": 200081,
          "sha512": "41217c460c8e94beb8f9087c5266f64e898a2750fd1093ce055eff58fedc43f4fb315b6beb80618f1364a54bacad0f037d87ddff18473abf7b45df45041c8832",
          "sha256": "7426b93c7fbc110cce47593dee3d4f718c2a9656bdb3ea5047fd2b62244ee519",
          "sha1": "413f48c427041b665236fc9f6e7a83e9791397d5",
          "md5": "56ba65f79d3bd4f8aee4c68545bdd3b7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "kandroidutils-1.6.0.aar",
          "url": "kandroidutils-1.6.0.aar",
          "size": 200081,
          "sha512": "41217c460c8e94beb8f9087c5266f64e898a2750fd1093ce055eff58fedc43f4fb315b6beb80618f1364a54bacad0f037d87ddff18473abf7b45df45041c8832",
          "sha256": "7426b93c7fbc110cce47593dee3d4f718c2a9656bdb3ea5047fd2b62244ee519",
          "sha1": "413f48c427041b665236fc9f6e7a83e9791397d5",
          "md5": "56ba65f79d3bd4f8aee4c68545bdd3b7"
        }
      ]
    }
  ]
}
