{
  "formatVersion": "1.1",
  "component": {
    "group": "me.kujio",
    "module": "kandroidutils",
    "version": "1.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "kandroidutils-1.3.5.aar",
          "url": "kandroidutils-1.3.5.aar",
          "size": 134384,
          "sha512": "1466218502482ddf087e6ccf2f9640f133768425d142f2e0af32a1b9db3ba0c9c8e9982b4c2f40df57a9b1b7db9c22559a2973be97c8fe08dfdec88c6e6d44c6",
          "sha256": "d8f9ca162bf9c1c434b014961c54c0e199e75d9286f735f58742f67bad3d87b6",
          "sha1": "fe55dc2ae52f04f71f77fdaeda81176502a409df",
          "md5": "ea1a974a212441849a8cffe9dcee529f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "kandroidutils-1.3.5.aar",
          "url": "kandroidutils-1.3.5.aar",
          "size": 134384,
          "sha512": "1466218502482ddf087e6ccf2f9640f133768425d142f2e0af32a1b9db3ba0c9c8e9982b4c2f40df57a9b1b7db9c22559a2973be97c8fe08dfdec88c6e6d44c6",
          "sha256": "d8f9ca162bf9c1c434b014961c54c0e199e75d9286f735f58742f67bad3d87b6",
          "sha1": "fe55dc2ae52f04f71f77fdaeda81176502a409df",
          "md5": "ea1a974a212441849a8cffe9dcee529f"
        }
      ]
    }
  ]
}
